version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:8100"
            - "5173:5173"
        networks:
            - mynet
        volumes:
            - ./:/app
        depends_on:
            - mysql
        entrypoint: [ "/bin/bash", "-c" ]
        command:
        - |
            composer install && npm install
            php artisan key:generate && php artisan migrate
            npm run dev
            php artisan serve --host=0.0.0.0 --port=8100
            
    mysql:
        image: mysql:5.7
        container_name: task_db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_TCP_PORT: ${DB_PORT}
        ports:
            - "3308:${DB_PORT}"
        networks:
            - mynet
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    
volumes:
  mysql_data:
networks:
  mynet:
    driver: bridge
